spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/payments?zeroDateTimeBehavior=convertToNull}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: '/'
